<?php

class Color
{

    /**
     * @throws Exception
     */
    public static function getHex(string $colorName): string
    {
        $mappings = self::getMapping();
        if (!array_key_exists($colorName, $mappings)) {
            throw new Exception('Color `' . $colorName . '` not found.');
        }

        $mappingsOverwrite = self::getMappingOverwrite();
        if (array_key_exists($colorName, $mappingsOverwrite)) {
            return $mappingsOverwrite[$colorName];
        }

        return $mappings[$colorName];
    }

    private static function getMappingOverwrite(): array
    {
        return [
            'black' => '#111111',
        ];
    }

    private static function getMapping(): array
    {
        return [
            'black' => '#000000',
            'white' => '#ffffff',

            'eyemaskwhite' => '#D7D7D7',

            'lightbrown' => '#AE8B61',
            'lightbrownlightest' => '#B69F81',
            'brown' => '#713F1D',
            'brownlightest' => '#8B532B',
            'lighterbrown' => '#DBB181',
            'lighterbrownlightest' => '#B69F81',
            'lighterbrownlightestfemale' => '#E6CBA9',
            'lighterbrownmale' => '#AE8B61',
            'lighterbrownmalelightest' => '#B69F81',
            'pale' => '#EAD9D8',
            'palelightest' => '#FFFFFF',
            'lightbrownmale' => '#DAB180',
            'lightbrownmalelightest' => '#E6CBA9',
            'zombiegreen' => '#7DA269',
            'zombiegray' => '#5E7153',
            'zombiered' => '#f53d3d',
            'zombielightgreen' => '#9CBB88',
            'frontbearddark' => '#68451F',
            'apeskinbrown' => '#342410',
            'apeskinbrownlight' => '#846F56',
            'alienskin' => '#C7FBFB',
            'alienskindarker' => '#9BE0E0',
            'alienskindarkest' => '#74BDBC',

            'mediumfemaleskinlips' => '#5F1E08',
            'lightbrowndarker' => '#86581E',
            'lightbrownlighter' => '#A67C47',
            'browndarker' => '#562600',
            'brownlighter' => '#723709',
            'femaleskinlightlips' => '#711010',
            'lighterbrowndarker' => '#A66E2C',
            'lighterbrownlighter' => '#D29D60',
            'femaledarklips' => '#4A1201',
            'palelighter' => '#CAB2B1',
            'paledarker' => '#A58D8C',
            'apeeyesdarkbrown' => '#6A563F',
            'apeeyesdarklighter' => '#A88C6B',

            '3dglasseswhite' => '#f0f0f0',
            'normalbeardblackmouthbrown' => '#86581d',
            'greeneyeshadowdarker' => '#507C33',
            'greeneyeshadowlighter' => '#5D8B43',
            'earringgold' => '#FFD925',
            'blondebob' => '#FFF68D',
            'mohawk' => '#A66E2C',
            'mohawklight' => '#85561D',
            'wildhair' => '#111110',
            'nerdglassesblue' => '#80DBDA',
            'pipelightbrown' => '#855113',
            'pipedarkbrown' => '#683C09',
            'bigshadespurple' => '#AD2160',
            'bigshadespurpledarker' => '#8C0C5B',
            'bigshadespurpledarkest' => '#690B45',
            'goatbrown' => '#A66E2C',
            'purpleeyeshadowdarker' => '#A32375',
            'purpleeyeshadowlighter' => '#B03285',
            'halfshaved' => '#111110',
            'doragdark' => '#4C4C4C',
            'doraglight' => '#636363',
            'clownblueeyes' => '#2C5195',
            'clownblueeyeslighter' => '#2758B1',
            'clownblueeyesdarker' => '#2A3E64',
            'messyhairblack' => '#111110',
            'luxuriousbeardbrown' => '#692F08',
            'clownnosered' => '#cc1714',
            'policecapblue' => '#26314A',
            'yellow' => '#FFD700',
            'bigbeard' => '#A66D2C',
            'blueeyeshadowdarker' => '#4F6A65',
            'blueeyeshadowlighter' => '#5D7975',
            'clowngreeneyes' => '#2C9541',
            'clowngreeneyeslighter' => '#28B042',
            'clowngreeneyesdarker' => '#296434',
            'straighthairdark' => '#111110',
            'blondeshort' => '#FEF68E',
            'purplelipstick' => '#CD00CA',
            'straighthairlight' => '#FEF68E',
            'pilothelmgreen' => '#2D6B62',
            'pilothelmgoggles' => '#80DBDA',
            'hotlipstick' => '#C42110',
            'stringyhair' => '#111110',
            'muttonchops' => '#A66D2C',
            'bluebandanaregular' => '#1A43C8',
            'bluebandanadarker' => '#1737A4',
            'bluebandanadarkest' => '#152B7B',
            'crazyhairred' => '#e04141',
            'classicsshadesdark' => '#5C390F',
            'classicsshadeslight' => '#C77515',
            'handlebarsdark' => '#A66D2C',
            'handlebarslight' => '#C28845',
            'darkhair' => '#111110',
            'peakspike' => '#111110',
            'cappurple' => '#9735cc',
            'cappurplelight' => '#B261DB',
            'vrgray' => '#8D8D8D',
            'vrgraylight' => '#B4B4B4',
            'frumpyhair' => '#111110',
            'frumpyhairlight' => '#2A2A2A',
            'cigarettewhite' => '#C6C6C6',
            'cigarettered' => '#E25B26',
            'cigarettesmoke' => '#eeeeee',
            'normalbeard' => '#A66D2C',
            'redmohawk' => '#e04141',
            'chinstrap' => '#A66D2C',
            'knittedcap' => '#C94E10',
            'knittedcapdark' => '#93370A',
            'fedorahat' => '#3D2F1E',
            'shadowbeard' => '#4F2C15',
            'straighthair' => '#51360D',
            'hoodiegray' => '#555555',
            'headbandblue' => '#196DD5',
            'cowboyhat' => '#784B12',
            'cowboyhatdark' => '#4F2F05',
            'tasslehatblue' => '#00557F',
            'tasslehatgreen' => '#229000',
            'blue' => '#328DFD',
            'red' => '#FD3132',
            'crazyhair' => '#e04141',
            'shadowbeardbrown' => '#281C0A',
            'shadowbeardlighthuman' => '#987C59',
            'shadowbeardbrownlighthuman' => '#281C0A',
            'shadowbearddarkhuman' => '#4F2C15',
            'shadowbeardbrowndarkhuman' => '#281C0A',
            'shadowbeardzombie' => '#577149',
            'shadowbeardbrownzombie' => '#281A09',
            'mustachezombie' => '#32412A',
            'mustache' => '#5E5757',
            'vapegray' => '#595959',
            'vapeblue' => '#0040FF',
            'pink' => '#FF8EBD',
            'weldinggogglesdark' => '#1C1A00',
            'weldinggoggleslight' => '#534C00',
            'weldinggogglesblue' => '#80DBDA',
            'mohawkthingray' => '#555555',
            'tiarayellow' => '#FFBA00',
            'tiaraorange' => '#FF2A00',
            'capforwardgraydarker' => '#353535',
            'capforwardgray' => '#515151',
            'gold' => '#FFC925',
            'purplehair' => '#9430e6',
            'beanieblue' => '#035FC2',
            'beanieyellow' => '#E3EB14',
            'beaniered' => '#D60305',
            'beaniegreen' => '#3BC202',
            'clowngreenhair' => '#5fc76d',
            'pigtailsyellow' => '#FFD825',
            'silver' => '#DFDFDF',
            'shadowbeardalbinohuman' => '#A39697',
            'shadowbeardbrownalbinohuman' => '#281C0A',
            'mustachealbinohuman' => '#5E5757',
            'mustachedarkhuman' => '#2D190C',
            'frontbeard' => '#A66D2C',
            'rosycheeksdarkhuman' => '#753B1B',
            'rosycheekszombie' => '#8F8154',
            'orangeside' => '#f0762b',
            'wildblonde' => '#FEF68E',
            'mustachelighthuman' => '#574733',
            'palelips' => '#701011',
            'shadowbeardmediumhuman' => '#796144',
            'shadowbeardbrownmediumhuman' => '#281C0A',
            'tophatred' => '#DC1D1D',
            'medicalmask' => '#C9C9C9',
            'medicalmaskdark' => '#B1B1B1',
            'rosycheekslighthuman' => '#D09C6E',
            'mustachemediumhuman' => '#463827',
            'rosycheeksmediumhuman' => '#AA7B54',
            'rosycheeksalbinohuman' => '#DDBEBA',
        ];
    }
}
